import {
	Archive,
	Bell,
	Blocks,
	Boxes,
	Building2,
	ChartLine,
	Code,
	Cursor,
	Database,
	Eye,
	FileUp,
	Filter,
	FolderKanban,
	Fingerprint,
	Globe,
	History,
	Images,
	KeyRound,
	Layers,
	LayoutDashboard,
	LayoutTemplate,
	Link2,
	Lock,
	MonitorSmartphone,
	PanelLeft,
	Pencil,
	Plug,
	Search,
	ShieldCheck,
	Sigma,
	SlidersHorizontal,
	Sparkles,
	SquareStack,
	Table2,
	UserRound,
	Users,
	Webhook,
	Server,
	Zap,
	type IconType,
} from '@/components/ui/icons';
import type { Tone } from '@/lib/tones';

/**
 * Everything MINT does, grouped — the /features page reads this, and the
 * product tour picks from it. Add a feature here when it ships (and a line
 * to content/changelog.ts).
 */

/** `soon`: being built — shown with a Coming soon badge until it ships. */
export type Feature = { icon: IconType; title: string; body: string; guide?: string; soon?: boolean };
export type FeatureGroup = { id: string; title: string; lead: string; color: Tone; features: Feature[] };

export const FEATURE_GROUPS: FeatureGroup[] = [
	{
		id: 'backend',
		color: 'cyan',
		title: 'Backend',
		lead: 'Backend as a service — live the moment you save a model.',
		features: [
			{ icon: Database, title: 'Database', body: 'Every model is a real, validated collection — relations, formulas, defaults and allowed values.', guide: 'models' },
			{ icon: Code, title: 'REST API per model', body: 'List, read, create, update and delete — you choose, per model, and who may call it.', guide: 'public-api' },
			{ icon: UserRound, title: 'Auth', body: 'Accounts for your team, and sign-up and sign-in for your customers.', guide: 'customers' },
			{ icon: Images, title: 'Storage', body: 'Images, videos and files in a media library, per project or shared.', guide: 'media' },
			{ icon: Pencil, title: 'Visual data editor', body: 'Tables and forms for every model; bulk edits, import, export and undo.', guide: 'records' },
			{ icon: Plug, title: 'MCP for AI', body: 'Your AI assistant builds and queries the backend through a scoped key.', guide: 'connect-ai' },
		],
	},
	{
		id: 'build',
		color: 'emerald',
		title: 'Build',
		lead: 'Building blocks for backends, admin panels and back offices.',
		features: [
			{
				icon: Layers,
				title: 'Templates',
				body: 'Start a project from a ready-made app, API or website — a CRM, a booking API, a shop — and edit everything. Or start from scratch.',
				guide: 'projects',
			},
			{
				icon: Boxes,
				title: 'Models',
				body: 'Describe a thing — a customer, a room, an order — and get its table, form, filters and page.',
				guide: 'models',
			},
			{
				icon: Link2,
				title: 'Linked records',
				body: 'Point a booking at its guest and its room. Linked records open from a chip, wherever they appear.',
				guide: 'models#models-links',
			},
			{
				icon: Sigma,
				title: 'Formulas',
				body: 'Fields that calculate themselves from other fields, kept up to date on every change.',
				guide: 'models#models-fields',
			},
			{
				icon: LayoutTemplate,
				title: 'Pages',
				body: 'Columns, filters, form sections and detail-page tabs — tuned in a draft, then published.',
				guide: 'pages',
			},
			{
				icon: SlidersHorizontal,
				title: 'Conditional fields',
				body: 'Show a field only when it applies: a cancellation reason only on cancelled bookings.',
				guide: 'pages#form',
			},
			{
				icon: PanelLeft,
				title: 'Sidebar',
				body: 'Arrange sections and pages, pick their icons, and decide who sees each one.',
				guide: 'sidebar',
			},
			{
				icon: LayoutDashboard,
				title: 'Dashboard',
				body: 'Numbers, charts and recent lists from your models on the project’s home page.',
				guide: 'dashboard',
			},
			{
				icon: Sparkles,
				title: 'Build with AI',
				body: 'Describe a model in a sentence; AI drafts the fields, links and formulas for you to check.',
				guide: 'connect-ai',
			},
		],
	},
	{
		id: 'work',
		color: 'sky',
		title: 'Work',
		lead: 'The everyday tools your team uses in every table.',
		features: [
			{ icon: Search, title: 'Search & filters', body: 'Find anything fast and filter by any field — dates, options, links and more.', guide: 'records#find' },
			{ icon: SquareStack, title: 'Bulk actions', body: 'Edit, archive or merge many rows at once — merges repoint every link.', guide: 'records#bulk' },
			{ icon: FileUp, title: 'Import & export', body: 'Bring a spreadsheet in, all-or-nothing, and export any view.', guide: 'records' },
			{ icon: History, title: 'History & undo', body: 'Every change to every record, with who made it and when — and an undo.', guide: 'records#history' },
			{ icon: Archive, title: 'Archive', body: 'Hide a record everywhere without losing it; bring it back anytime.', guide: 'records#bulk' },
			{ icon: Bell, title: 'Notifications', body: 'Hear about what matters: a new sign-up, an order from your site, a shared record.' },
			{ icon: Images, title: 'Media', body: 'A drive for images, videos and files — folders, links and a trash.', guide: 'media' },
			{ icon: Lock, title: 'Private records', body: 'Records only their owner — or the people they share with — can open.', guide: 'models#models-access' },
		],
	},
	{
		id: 'team',
		color: 'amber',
		title: 'Team',
		lead: 'Everyone in, each with the right access.',
		features: [
			{ icon: Building2, title: 'Organizations', body: 'One for your company, with as many projects as you need.', guide: 'organization' },
			{ icon: Users, title: 'Roles', body: 'Standard permissions — view, add, edit, delete, build — in plain words.', guide: 'organization#roles' },
			{ icon: FolderKanban, title: 'Project access', body: 'Give someone every project, or only the ones they work in.', guide: 'organization#project-access' },
			{ icon: Fingerprint, title: 'Passkeys & two-step', body: 'Sign in with a passkey or an email code on top of a password.', guide: 'account#overview' },
			{ icon: MonitorSmartphone, title: 'Signed-in devices', body: 'See every device on your account and sign any of them out.', guide: 'account#devices' },
			{ icon: ShieldCheck, title: 'Isolation', body: 'Every project’s data is scoped to its organization, on every request.' },
		],
	},
	{
		id: 'live',
		color: 'cyan',
		title: 'Go live',
		lead: 'Your data, on your own site and app.',
		features: [
			{ icon: Webhook, title: 'Public API', body: 'Turn on list, read, create, update or delete per model — no server to run.', guide: 'public-api' },
			{ icon: Filter, title: 'Filters & search', body: 'Paging, sorting, field filters, date ranges and search on every list.', guide: 'public-api#filters' },
			{ icon: Code, title: 'API reference & tester', body: 'Each project documents its own API, with curl and fetch examples and a tester to try calls live.', guide: 'public-api' },
			{ icon: Server, title: 'API projects', body: 'A project laid out as a back end: its API first, a dashboard of endpoints and recent calls.', guide: 'projects#api' },
			{ icon: Zap, title: 'Webhooks', body: 'Your server hears about every new, changed or deleted record — signed, retried and logged.', guide: 'public-api#webhooks' },
			{ icon: UserRound, title: 'Customer accounts', body: 'Sign-up and sign-in for your customers; they see only their own records.', guide: 'customers' },
			{ icon: Blocks, title: 'Site widgets', body: 'One script tag puts sign-in, a cart and checkout on your own site — styled to match, priced by our server, paid into your own Stripe.', guide: 'widgets' },
			{
				icon: Cursor,
				title: 'Site builder',
				body: 'Build your site visually: add blocks and ready-made sections, drag them into place, click any part to change it, add pop-ups and drawers, then publish. Drafts stay private until you do.',
				guide: 'site-builder',
				soon: true,
			},
			{ icon: Globe, title: 'Website kit', body: 'Pages, per-page SEO and content blocks — rendered on your site in two calls.', guide: 'websites' },
			{ icon: ChartLine, title: 'Analytics', body: 'Visitors, pages, sources and events — without cookies.', guide: 'analytics' },
		],
	},
	{
		id: 'ai',
		color: 'violet',
		title: 'AI',
		lead: 'Bring the assistant you already use.',
		features: [
			{ icon: Plug, title: 'Connect your AI', body: 'Claude, ChatGPT and other assistants plan and build in a project over MCP.', guide: 'connect-ai' },
			{ icon: KeyRound, title: 'Project keys', body: 'A key per connection, for one project — see when it was last used, revoke it at once.', guide: 'connect-ai#mcp-keys' },
			{ icon: Blocks, title: 'Plan, then build', body: 'The assistant drafts a plan you can check before anything is built.', guide: 'connect-ai#conversation' },
			{ icon: Table2, title: 'Works with your data', body: 'Ask for a dashboard, a filter or a new field on the models you already have.' },
			{ icon: ChartLine, title: 'Analyze with any AI', body: 'A read-only key lets your assistant answer questions from your live records — counts, totals, breakdowns.', guide: 'connect-ai#tools' },
			{ icon: Eye, title: 'Everything recorded', body: 'Changes made by an assistant land in history like anyone else’s.' },
		],
	},
];
